#
---
- name: Update node1 servers
  hosts: node1


  tasks:
  - name: Create Directory
    file: 
      path:  /home/ec2-user/new_dir
      state: directory

  - name: Create Directory
    file: 
      path:  /home/ec2-user/new_dir_1
      state: directory

  - name: Update node2 servers
    hosts: node2


  tasks:
  - name: Create Directory
    file: 
      path: /home/ec2-user/new_dir_1
      state: directory

 
  tasks:
  - name: Create Directory
    file: 
      path:  /home/ec2-user/new_dir_2
      state: directory


  - name: Update nodes servers
    hosts: nodes


  tasks:
  - name: Create Directory
    file: 
      path:  /home/ec2-user/new_dir_nodes1
      state: directory

  - name: Create Directory
    file: 
      path:  /home/ec2-user/new_dir_nodes2
      state: directory

... 


