---
- name: Update node1 servers
  hosts: node1
  tasks:
    - name: Create Directory on node1
      file: 
        path: /home/ec2-user/new_dir
        state: directory

    - name: Create Another Directory on node1
      file: 
        path: /home/ec2-user/new_dir_1
        state: directory

- name: Update node2 servers
  hosts: node2
  tasks:
    - name: Create Directory on node2
      file: 
        path: /home/ec2-user/new_dir_1
        state: directory

    - name: Create Another Directory on node2
      file: 
        path: /home/ec2-user/new_dir_2
        state: directory

- name: Update all nodes servers
  hosts: nodes
  tasks:
    - name: Create Directory on nodes
      file: 
        path: /home/ec2-user/new_dir_nodes1
        state: directory

    - name: Create Another Directory on nodes
      file: 
        path: /home/ec2-user/new_dir_nodes2
        state: directory
...