---
- name: Install HTTP server
  hosts: node1
  become: yes

  tasks:
    - name: Install HTTPD
      yum:   
        name: httpd 
        state: present 

    - name: start Httpd
      service: 
        name: httpd
        state: started

    - name: Enabled Httpd
      service: 
        name: httpd
        enabled: yes
        
...