---
- name: Deploy Web App
  hosts: node1
  become: yes

  tasks:
    - name: Install Git
      yum:   
        name: git 
        state: present 

    - name: Most code
      git: 
        repo: https://github.com/TowehE/Ansible.git
        dest: /var/www/html

   
...