---
- name: Deploy Food Web App
  hosts: node1
  become: yes

  tasks:
    - name: Install Git
      yum:   
        name: git 
        state: present 

    - name: Most code
      git: 
        repo: https://github.com/CeeyIT-Solutions/food3.git
        dest: /var/www/html

   
...