---
- name: Variables Demo
  hosts: nodes
  become: yes
  vars:
    myusername: Toweh

  tasks:
  - name: Update Dynamic page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynam.html
...
